purge_plugin_purger:
  type: mapping
  label: 'Plugin'
  mapping:
    instance_id:
      type: string
      label: 'Instance ID'
      translatable: false
    plugin_id:
      type: string
      label: 'Plugin ID'
      translatable: false
purge_plugin_processor:
  type: mapping
  label: 'Plugin'
  mapping:
    plugin_id:
      type: string
      label: 'Plugin ID'
      translatable: false
    status:
      type: bool
      label: 'Enabled or disabled'
      translatable: false
purge_plugin_queuer:
  type: mapping
  label: 'Plugin'
  mapping:
    plugin_id:
      type: string
      label: 'Plugin ID'
      translatable: false
    status:
      type: bool
      label: 'Enabled or disabled'
      translatable: false
