 # Schema for the configuration files of the Purge module.

purge.plugins:
  type: mapping
  label: 'Purge plugins'
  mapping:
    queue:
      type: string
      label: 'Queue plugin ID.'
      translatable: false
    purgers:
      type: sequence
      label: 'Enabled purgers.'
      sequence:
        - type: string
          label: 'Plugin ID'
      translatable: false
