 # Schema for the configuration files of the Purge module.

purge.queue:
  type: mapping
  label: 'Generic configuration options for the purge queue service.'
  mapping:

    # Defines which plugin provides the Purge queue, must be a valid plugin ID.
    plugin:
      translatable: false
      type: text
      label: 'Queue back-end'

purge.purger:
  type: mapping
  label: 'Generic configuration options for the purger service.'
  mapping:

    # Which plugins should execute external cache invalidations? The default
    # value 'automatic_detection' will load all available purgers in parallel,
    # any other value is assumed to be a comma-separated list of plugins to be
    # loaded, e.g.: 'purgera,purgerb'.
    plugins:
      translatable: false
      type: text
      label: 'Purger back-end(s)'