 # Schema for the configuration files of the Purge module.
purge.plugins:
  type: config_object
  label: 'Purge plugins'
  mapping:
    purgers:
      label: 'Enabled purger plugin instances.'
      type: sequence
      translatable: false
      sequence:
        type: mapping
        mapping:
          instance_id:
            type: string
          plugin_id:
            type: string
    processors:
      label: 'All known processor plugins (including disabled).'
      type: sequence
      translatable: false
      sequence:
        type: mapping
        mapping:
          plugin_id:
            type: string
          enabled:
            type: bool
    queuers:
      label: 'All known queuer plugins (including disabled).'
      type: sequence
      translatable: false
      sequence:
        type: mapping
        mapping:
          plugin_id:
            type: string
          enabled:
            type: bool
    queue:
      type: string
      label: 'The currently active queue plugin.'
      translatable: false
