# Schema for the configuration files of the purge_processor_lateruntime module.

purge_processor_lateruntime.settings:
  type: config_object
  label: 'Late runtime processor settings'
  mapping:
    always_check_queue:
      type: boolean
      label: 'Check database for queue items even if no invalidations were added during the request.'
